### ISSUE TITLE
Installation improovments

### ISSUE THREAD

**Issue by andreykhr** [alexey-detr/yandex-music-hotkeys#1]
Hi, recently I install your workflow and its work fine, but I got some troubles:

- To work this, I need enable JavaScript from apple events in safari. (Develop menu > Allow Javascript from Apple Events)
- Set shortcuts on every events in workflow. 

It would be great if this will be in README.md file. Installation section required)

**Comment by alexey-detr** [comment]
Thank you for the feedback! I agree, that would be nice to have an installation section, I'll add it soon 🙂

**Comment by alexey-detr** [comment]
Done.
